name: Create mrpack file

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create mrpack file
      run: python main.py ${{ github.repository }} ${{ github.ref_name }}
    - name: Delete existing tag if exists
      run: |
        git tag -d ${{ github.ref_name }} || true
        git push origin :refs/tags/${{ github.ref_name }} || true
    - name: Create Release
      id: create_release
      uses: comnoco/create-release-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.NEWTAG }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: pack.mrpack
        asset_name: pack.mrpack
        tag: ${{ env.NEWTAG }}
        overwrite: true